#! /bin/sh

bspc config border_width        3
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-1 -d 00
bspc monitor DP-2 -d 01
bspc monitor DVI-I-1-1 -d 10

bspc rule -a Zathura state=tiled
